Repository ktr0731/evans, pull requests merged in 2019-02, with the labels that each got.

#151 update CircleCI config
  .circleci/Dockerfile
  README.md
  tests/helper/server.go
Labels: bug, update

#152 Fix go.sum
  appveyor.yml
  go.mod
  go.sum
Labels: bug, update

#154 include the project dir to the workspace in the CircleCI environment
  .circleci/config.yml
Labels: bug

#156 fix attach_workspace
  .circleci/config.yml
Labels: bug

#149 Add TLS options
  README.md
  adapter/app/app.go
  adapter/grpc/cert/localhost-key.pem
  adapter/grpc/cert/localhost.pem
  adapter/grpc/cert/rootCA.pem
  adapter/grpc/grpc.go
  adapter/grpc/grpc_test.go
  adapter/grpc/testdata/cert/localhost-key.pem
  adapter/grpc/testdata/cert/localhost.pem
  adapter/grpc/testdata/cert/rootCA.pem
  adapter/grpc/web.go
  adapter/prompt/prompt.go
  config/config.go
  config/migrate.go
  config/migrate_test.go
  config/testdata/fixtures/create_a_default_global_config_if_both_of_global_and_local_config_are_not_found.golden.toml
  config/testdata/fixtures/load_a_global_config_if_local_config_is_not_found.golden.toml
  config/testdata/fixtures/load_a_local_config.golden.toml
  config/testdata/fixtures/will_be_apply_flags.golden.toml
  config/testdata/fixtures/will_be_apply_flags_but_local_config_doesnt_exist.golden.toml
  di/dependency.go
  di/dependency_test.go
  entity/grpc.go
  go.mod
  go.sum
  meta/meta.go
  tests/e2e/cli_test.go
  tests/e2e/repl_test.go
  tests/e2e/server.go
  tests/e2e/server/helloworld/helloworld.pb.go
  tests/e2e/server/server.go
  tests/e2e/testdata/cert/localhost-key.pem
  tests/e2e/testdata/cert/localhost.pem
  tests/e2e/testdata/cert/rootCA.pem
Labels: new feature, update

#158 Change usage of Reflection to get package information for Client
  adapter/grpc/reflection.go
  di/dependency.go
  entity/grpc.go
  tests/e2e/cli_test.go
  tests/e2e/repl_test.go
  tests/mock/entity/mock.go
Labels: enhancement

#159 set the package as default if package/service is only one
  config/testdata/fixtures/create_a_default_global_config_if_both_of_global_and_local_config_are_not_found.golden.toml
  di/dependency.go
  meta/meta.go
  tests/e2e/cli_test.go
  tests/e2e/e2e_test.go
  tests/e2e/repl_test.go
Labels: enhancement
